name: Deploy Bokportalen backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: |
         cd /var/www/bokportalen_backend
         npm ci

      - name: Build project
        run: |
         cd /var/www/bokportalen_backend
         npm run build

      - name: Move project to target directory
        run: |
          TARGET_DIR="/var/www/bokportalen_backend/"
          rm -rf ${TARGET_DIR:?}/*
          cp -r ./backend/dist/* "$TARGET_DIR"

      - name: Restart service
        run: |
          sudo systemctl restart bokportalen_backend.service
